### ISSUE TITLE
"show configuration snapshot" output is cut off

### ISSUE THREAD

**Issue by cs-1** [gmoisio/ansible-aos-stdlib#3]
Hi Gilbert,

we're using the current version of ansible-aos-stdlib from Ansible Galaxy. To get some state from the switch (OS6450 w/ AOS 6.7.2.113.R05 GA) I do the following:

```
- name: Get config from switch
  ale_aos_command: 
    host: "{{ inventory_hostname }}"
    username: XXXXXX
    password: "XXXXXX"
    command: show configuration snapshot
  register: configuration_snapshot
```

The command itself works, however, it only shows the first part of the configuration. It doesn't register the whole output of `show configuration snapshot`. I'm not entirely sure but I suspect that ansible-aos-stdlib maybe doesn't issue `no more` before running the command with `ale_aos_command`. Or did I miss something? Thanks!

Christian

**Comment by gmoisio** [comment]
Hi Christian, thank you for your message.
Yes you missed something... :-)
On AOS6, there is a limitation that you can avoid with the option: timing: True
Have fun!
Regards

**Comment by cs-1** [comment]
Hi Gilbert,

thanks for the info. I suspect that `send_command_timing` is a netmiko option. Since I'm not familiar with netmiko I didn't understand the option. It might be a good idea to clarify the option in the documentation.

Thanks in any case for the quick reply, I'm currently "marrying" NetBox with our AOS switches. It's quite difficult because there's no idempotent way to apply a configuration to a switch except for rebooting the switch from a pre-written config. That's a pity but there's no other way in AOS that I see (e.g. create candidate config and apply it and let AOS sort out the diffs; works with Juniper/JUNOS, Pica8/PICOS etc.).

Thanks for providing this Ansible module, it's very helpful.

Christian

**Comment by gmoisio** [comment]
Hi Christian, I spoke about an option of my module:

```
    timing:
        description:
            - Boolean to run send_command_timing instead of send_command
        required: false
        default: false
```

You can read the README that is on the root of the repo.
I'm not sure to understand your remark about AOS/NetBox, the configuration is dynamic on AOS...

Regards
